complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 0
  ComplexInterface:
    active: false
    threshold: 0
    includeStaticDeclarations: false
    includePrivateDeclarations: false
    ignoreOverloaded: false
  ComplexMethod:
    active: true
    threshold: 0
    ignoreSingleWhenExpression: false
    ignoreSimpleWhenEntries: false
    ignoreNestingFunctions: false
    nestingFunctions:
      - 'also'
      - 'apply'
      - 'forEach'
      - 'isNotNull'
      - 'ifNull'
      - 'let'
      - 'run'
      - 'use'
      - 'with'

style:
  active: true

detekt-hint:
  LackOfCohesionMethods:
    active: true
    threshold: "0.0"